gateways:
  maas-default-gateway:
    listeners:
      http:
        hostname: "maas.apps.{{ .Values.global.cluster.name }}.{{ .Values.global.cluster.baseDomain }}"
      https:
        hostname: "maas.apps.{{ .Values.global.cluster.name }}.{{ .Values.global.cluster.baseDomain }}"
        certificate:
          create: true
          secretName: maas-default-gateway-venafi-tls
          duration: 17520h
          issuerRef:
            group: cert-manager.io
            kind: ClusterIssuer
            name: venafi-tpp-cluster-issuer
        tls:
          certificateRefs:
            - group: ""
              kind: Secret
              name: maas-default-gateway-venafi-tls
