{{- with .Values.dataScienceClusterInitialization }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apply-dsci
  namespace: redhat-ods-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apply-dsci
rules:
  - apiGroups: ["dscinitialization.opendatahub.io"]
    resources: ["dscinitializations"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apply-dsci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apply-dsci
subjects:
  - kind: ServiceAccount
    name: apply-dsci
    namespace: redhat-ods-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apply-dsci
  namespace: redhat-ods-operator
data:
  dsci.yaml: |
    ---
    apiVersion: dscinitialization.opendatahub.io/v2
    kind: DSCInitialization
    metadata:
      name: default-dsci
    spec:
      {{- toYaml . | nindent 6 }}
  apply-dsci.sh: |
{{ $.Files.Get "files/apply-dsci.sh" | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: apply-dsci
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 12
  template:
    spec:
      serviceAccountName: apply-dsci
      restartPolicy: Never
      containers:
        - name: apply-dsci
          image: {{ $.Values.global.toolsImage }}
          imagePullPolicy: IfNotPresent
          command: ["/scripts/apply-dsci.sh"]
          volumeMounts:
            - name: config
              mountPath: /config
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: config
          configMap:
            name: apply-dsci
        - name: scripts
          configMap:
            name: apply-dsci
            items:
              - key: apply-dsci.sh
                path: apply-dsci.sh
            defaultMode: 493
{{- end }}
