apiVersion: v1
kind: ServiceAccount
metadata:
  name: apply-nfd-instance
  namespace: openshift-nfd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apply-nfd-instance
  namespace: openshift-nfd
rules:
  - apiGroups: ["nfd.openshift.io"]
    resources: ["nodefeaturediscoveries"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apply-nfd-instance
  namespace: openshift-nfd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apply-nfd-instance
subjects:
  - kind: ServiceAccount
    name: apply-nfd-instance
    namespace: openshift-nfd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apply-nfd-instance
  namespace: openshift-nfd
data:
  nodefeaturediscovery.yaml: |
    ---
    apiVersion: nfd.openshift.io/v1
    kind: NodeFeatureDiscovery
    metadata:
      name: nfd-instance
      namespace: openshift-nfd
    spec:
      instance: ""
      {{- with .Values.nfd.operand }}
      operand:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      prunerOnDelete: {{ .Values.nfd.prunerOnDelete }}
      topologyUpdater: {{ .Values.nfd.topologyUpdater }}
      workerConfig:
        configData: |-
          {{- toYaml .Values.nfd.configData | nindent 10 }}
  apply-nodefeaturediscovery.sh: |
{{ .Files.Get "files/apply-nodefeaturediscovery.sh" | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: apply-nfd-instance
  namespace: openshift-nfd
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 12
  template:
    spec:
      serviceAccountName: apply-nfd-instance
      restartPolicy: Never
      containers:
        - name: apply-nfd-instance
          image: {{ .Values.global.toolsImage }}
          imagePullPolicy: IfNotPresent
          command: ["/scripts/apply-nodefeaturediscovery.sh"]
          volumeMounts:
            - name: config
              mountPath: /config
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: config
          configMap:
            name: apply-nfd-instance
        - name: scripts
          configMap:
            name: apply-nfd-instance
            items:
              - key: apply-nodefeaturediscovery.sh
                path: apply-nodefeaturediscovery.sh
            defaultMode: 493
